spring.application.name=Personal-Cloud

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:personal_cloud}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${JWT_SECRET:this-is-a-super-secret-key-for-jwt-signing-which-should-be-changed-in-production}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

# AWS
app.aws.region=${AWS_REGION:eu-north-1}
app.s3.bucket=${S3_BUCKET_NAME:personal-cloud-project}

# Multipart
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Frontend
app.frontend.url=${FRONTEND_URL:http://localhost:3000}
